apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /app
      - name: con2
        image: tomcat:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: myvol
          mountPath: /app
      volumes:
      - name: myvol
        hostPath:
          path: /data

