apiVersion: v1
kind: Pod
metadata:
  labels:
    app: apple
  name: apple
spec:
  containers:
  - image: nginx
    name: con1
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - myapp
        topologyKey: kubernetes.io/hostname 
