apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - image: nginx
    name: con1
    ports:
    - containerPort: 80
    resources:
       requests:
         memory: "64Mi"
         cpu: "200m"
       limits:
         memory: "256Mi"
         cpu: "500m"
  - image: tomcat 
    name: con2
    ports:
    - containerPort: 8080


