apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod-tt-2
spec:
  containers:
  - image: nginx
    name: con1
    ports:
    - containerPort: 80
  tolerations:
  - key: color
    operator: Equal
    value: green
    effect: NoExecute

