apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod-tt
spec:
  containers:
  - image: nginx
    name: con1
    ports:
    - containerPort: 80
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Equal
    effect: NoSchedule 


