apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql-pod
spec:
  containers:
  - image: mysql:5.7
    name: con2
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: mydb

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306

